Fronttends/FreeCourse.Web/Models/Baskets/BasketItemViewModel.cs
namespace FreeCourse.Web.Models.Baskets
{
    public class BasketItemViewModel
    {
        private decimal? DiscountAppliedPrice;
        public int Quantity { get; set; } = 1;

        public string CourseId { get; set; }
        public string CourseName { get; set; }

        public decimal Price { get; set; }

        public decimal GetCurrentPrice
        {
            get => DiscountAppliedPrice != null ? DiscountAppliedPrice.Value : Price;
        }

        public void AppliedDiscount(decimal discountPrice)
        {
            DiscountAppliedPrice = discountPrice;
        }
    }
}

Fronttends/FreeCourse.Web/Models/Baskets/BasketViewModel.cs
namespace FreeCourse.Web.Models.Baskets
{
    public class BasketViewModel
    {
        private List<BasketItemViewModel> _basketItems;

        public BasketViewModel()
        {
            _basketItems = new List<BasketItemViewModel>();
        }

        public string UserId { get; set; } = "";

        public string DiscountCode { get; set; } = "";

        public int? DiscountRate { get; set; }
       
        public List<BasketItemViewModel> BasketItems
        {
            get
            {
                if (HasDiscount)
                {
                    //Örnek kurs fiyat 100 TL indirim %10
                    _basketItems.ForEach(x =>
                    {
                        var discountPrice = x.Price * ((decimal)DiscountRate.Value / 100);
                        x.AppliedDiscount(Math.Round(x.Price - discountPrice, 2));
                    });
                }
                return _basketItems;
            }
            set
            {
                _basketItems = value;
            }
        }

        public decimal TotalPrice
        {
            get => _basketItems.Sum(x => x.GetCurrentPrice);
        }

        public bool HasDiscount
        {
            get => !string.IsNullOrEmpty(DiscountCode) && DiscountRate.HasValue;
        }

        public void CancelDiscount()
        {
            DiscountCode = "";
            DiscountRate = null;
        }

        public void ApplyDiscount(string code, int rate)
        {
            DiscountCode = code;
            DiscountRate = rate;
        }
    }



}

Fronttends/FreeCourse.Web/Controllers/BasketController.cs
using FreeCourse.Shared.Services;
using FreeCourse.Web.Models.Baskets;
using FreeCourse.Web.Models.Discounts;
using FreeCourse.Web.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FreeCourse.Web.Controllers
{
    [Authorize]
    public class BasketController : Controller
    {
        private readonly ICatalogService _catalogService;
        private readonly IBasketService _basketService;

        public BasketController(ICatalogService catalogService, IBasketService basketService)
        {
            _catalogService = catalogService;
            _basketService = basketService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _basketService.Get());
        }

        public async Task<IActionResult> AddBasketItem(string courseId)
        {

            // todo: basket servis redis doğru çalışmıyor
            var course = await _catalogService.GetByCourseId(courseId);
            var basketItem = new BasketItemViewModel()
            {
                CourseId = courseId,
                CourseName = course.Name,
                Price = course.Price
                
            };
            
            await _basketService.AddBasketItem(basketItem);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> RemoveBasketItem(string courseId)
        {
            await _basketService.RemoveBasketItem(courseId);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> ApplyDiscount(DiscountApplyInput discountApplyInput)
        {
            if (!ModelState.IsValid)
            {
                TempData["discountError"] = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage).First();
                return RedirectToAction(nameof(Index));
            }
            var discountStatus = await _basketService.ApplyDiscount(discountApplyInput.Code);

            TempData["discountStatus"] = discountStatus;
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> CancelAppliedDiscount()
        {
            await _basketService.CancelApplyDiscount();
            return RedirectToAction(nameof(Index));
        }
    }
}

Fronttends/FreeCourse.Web/Controllers/OrderController.cs
using FreeCourse.Web.Models.Orders;
using FreeCourse.Web.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace FreeCourse.Web.Controllers
{
    public class OrderController : Controller
    {
        private readonly IBasketService _basketService;
        private readonly IOrderService _orderService;

        public OrderController(IBasketService basketService, IOrderService orderService)
        {
            _basketService = basketService;
            _orderService = orderService;
        }

        public async Task<IActionResult> Checkout()
        {
            var basket = await _basketService.Get();
            ViewBag.basket = basket;
            return View(new CheckoutInfoInput());
        }

        [HttpPost]
        public async Task<IActionResult> Checkout(CheckoutInfoInput checkoutInfoInput)
        {

            //// 1. yöntem asenkron ileitişim
            // var orderStatus = await _orderService.CreateOrder(checkoutInfoInput);
            //if (!orderStatus.IsSuccessful)
            //{
            //    var basket = await _basketService.Get();
            //    ViewBag.basket = basket;
            //    ViewBag.error = orderStatus.Error;
            //    return View();
            //}
            // return RedirectToAction(nameof(SuccessfulCheckout), new {orderId=orderStatus.OrderId});


            // 2. yol asenktron iletişim. Rabbit MQ'ya gönderiyoruz
            // Order servis Rabbit MQ'yu dinleyip o şekilde orderi oluşturacak.
            var orderSuspend = await _orderService.SuspendOrder(checkoutInfoInput);
            if (!orderSuspend.IsSuccessful)
            {
                var basket = await _basketService.Get();
                ViewBag.basket = basket;
                ViewBag.error = orderSuspend.Error;
                return View();
            }
            // burada senkron yöntemde orderId dönüyoruz. asenkronda döndürmeğim için şimdilik 
            // bu şekilde randon değer ürettim. İleride Payment Id dönülebilir.
            return RedirectToAction(nameof(SuccessfulCheckout), new { orderId =new Random().Next(1,1000) });
        }

        public IActionResult SuccessfulCheckout(int orderId)
        {
            ViewBag.orderId = orderId;
            return View();
        }

        public async Task<IActionResult> CheckoutHistory()
        {
            
            return View(await _orderService.GetOrder());
        }

    }
}

Fronttends/FreeCourse.Web/Views/Basket/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

@model BasketViewModel

<div class="row">

    <div class="col-md-8 offset-md-2">

        <div class="card">
            <div class="card-body">

                <h5 class="card-title">Sepet</h5>

                @if (Model != null && Model.BasketItems.Any())
                {
                    <table class="table table-striped">

                        <tr>
                            <th>Kurs isim</th>
                            <th>Kurs fiyat</th>
                            <th>İşlemler</th>
                        </tr>

                        @foreach (var item in Model.BasketItems)
                        {
                            <tr>
                                <td>@item.CourseName</td>
                                <td>
                                    @item.GetCurrentPrice TL @(Model.HasDiscount ? $"(% {Model.DiscountRate.Value} uygulandı)" : "")
                                </td>
                                <td>
                                    <a class="btn btn-danger" asp-controller="Basket" asp-action="RemoveBasketItem" asp-route-courseId="@item.CourseId">Sil</a>
                                </td>
                            </tr>
                        }

                        @if (Model.HasDiscount)
                        {

                            <tr>
                                <td>Indirim oranı</td>
                                <th colspan="2"> % @Model.DiscountRate.Value</th>
                            </tr>

                        }

                        <tr>
                            <td>@(Model.HasDiscount ? "İndirimli fiyat" : "Toplam fiyat")</td>
                            <th colspan="2">@Model.TotalPrice TL</th>
                        </tr>
                    </table>

                    <form asp-controller="Basket" asp-action="ApplyDiscount">
                        @if (Model.HasDiscount)
                        {
                            <div class="alert alert-success">
                                "@Model.DiscountCode" indirim kodu uygulandı
                                <a asp-controller="Basket" asp-action="CancelAppliedDiscount"> (iptal et)</a>
                            </div>

                        }

                        <div class="input-group mb-3">
                            <input type="text" class="form-control" name="DiscountApplyInput.Code">
                            <button class="btn btn-outline-secondary" type="submit">Uygula</button>
                        </div>

                        @if (TempData["discountStatus"] != null && (bool)TempData["discountStatus"] == false)
                        {
                            <div class="text-danger">indirim kodu geçersiz</div>
                        }
                        @if (TempData["discountError"] != null)
                        {
                            <div class="text-danger">@TempData["discountError"]</div>
                        }
                    </form>
                    <a class="btn btn-success" asp-controller="Order" asp-action="Checkout">Ödeme bilgileri</a>
                    <a class="btn btn-warning" asp-controller="Home" asp-action="Index">Kursları incelemeye devam et</a>
                }
                else
                {
                    <div class="alert alert-info">Sepet boş</div>
                }
            </div>
        </div>
    </div>
</div>